default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: less_than_trucking_development

test:
  <<: *default
  database: less_than_trucking_test
